apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
      - name: react-container
        image: vasilijed/counter-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://backend-service:8000"
