name: Deploy Frontend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push to Docker Hub
      run: |
        docker build -t vasilijed/counter-frontend:${{ github.sha }} .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push vasilijed/counter-frontend:${{ github.sha }}

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3

    - name: Deploy frontend to namespace
      run: |
        kubectl create namespace ${{ github.ref_name }} --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f k8s/ -n ${{ github.ref_name }}
        kubectl set image deployment/counter-frontend-deployment \
          frontend-container=vasilijed/counter-frontend:${{ github.sha }} -n ${{ github.ref_name }}