name: Deploy Frontend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Frontend Docker image
      run: |
        docker build -t counter-frontend:${{ github.sha }} .

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker

    - name: Load frontend image to Minikube
      run: |
        minikube image load counter-frontend:${{ github.sha }}

    - name: Deploy frontend to namespace
      run: |
        kubectl create namespace ${{ github.ref_name }} --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f k8s/ -n ${{ github.ref_name }}
        kubectl set image deployment/counter-frontend-deployment \
          frontend-container=counter-frontend:${{ github.sha }} -n ${{ github.ref_name }} || true
        
    - name: Verify frontend deployment
      run: |
        kubectl rollout status deployment/counter-frontend-deployment -n ${{ github.ref_name }} --timeout=300s
        echo " Frontend deployed to ${{ github.ref_name }} namespace"