name: Deploy Backend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-backend:
    runs-on: self-hosted
    timeout-minutes: 3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      shell: cmd
      run: |
        docker build -t vasilijed/counter-backend:${{ github.sha }} .
        docker tag vasilijed/counter-backend:${{ github.sha }} vasilijed/counter-backend:latest

    - name: Push Docker image
      shell: cmd
      run: |
        docker push vasilijed/counter-backend:${{ github.sha }}
        docker push vasilijed/counter-backend:latest

    - name: Restart deployment
      shell: cmd
      run: |
        k3d kubeconfig get ci-cluster > %USERPROFILE%\.kube\config
        kubectl rollout restart deployment/counter-backend-deployment -n %GITHUB_REF_NAME%
