name: Deploy Frontend

on:
  push:
    branches: [dev, qa, uat, master]

jobs:
  deploy-frontend:
    runs-on: self-hosted
    timeout-minutes: 3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      shell: cmd
      run: |
        docker build -t vasilijed/counter-frontend:${{ github.sha }} .
        docker tag vasilijed/counter-frontend:${{ github.sha }} vasilijed/counter-frontend:latest

    - name: Push Docker image
      shell: cmd
      run: |
        docker push vasilijed/counter-frontend:${{ github.sha }}
        docker push vasilijed/counter-frontend:latest

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Init with Terraform  
      run: |
        terraform init -no-color

    - name: Apply with Terraform  
      run: |
        terraform apply -auto-approve -no-color

    - name: Restart Frontend Deployment
      run: |
        kubectl rollout restart deployment/counter-frontend-deployment -n master
